### ISSUE TITLE
Issue with example execution

### ISSUE THREAD

**Issue by awoods** [mconlon17/vivo-sample-data-generator#1]
Running the following:
```
python3 sample-data-generator.py
```

..results in:
> Traceback (most recent call last):
  File "sample-data-generator.py", line 467, in <module>
    main()
  File "sample-data-generator.py", line 447, in main
    max_works_per_faculty))):
TypeError: only integer scalar arrays can be converted to a scalar index

Is there another example execution command that should be run?

**Comment by mconlon17** [comment]
Thanks for giving this a try.

The error is fixed with commit https://github.com/mconlon17/vivo-sample-data-generator/commit/3d90fc09228326eab44860e14f64ff00728d9237

I had repaired this some time back, but never pushed the fixed to the master. Should be good now.

Please let me know if this resolves the issue and then this can be closed.

**Comment by awoods** [comment]
```
$ python3 sample-data-generator.py
```
> vivo.mydomain.edu 1 University; 1 colleges; 1 departments; 12 people; 18 works; 1445 triples in language en 0.95 seconds

Looks good! Thanks for the quick turnaround.
